# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

title: Tech at GSA
email: cto@gsa.gov
description: >
  The GSA Office of the CTO utilizes collaborative practices and modern IT tools to facilitate a new GSA.
baseurl: ""
url: "https://tech.gsa.gov"
markdown: kramdown
include:
  - '_pages'
exclude:
  - 'README.md'
  - 'LICENSE.md'
  - 'Rakefile'
  - 'Gemfile'
  - 'Gemfile.lock'
  - 'package.json'
  - 'node_modules'
  - 'gulpfile.js'
  - '_test'
  - '.circleci'
  - 'vendor'
  - 'Dockerfile'
  - 'docker-run.sh'
plugins:
  - jekyll-sitemap

collections:
  team:
    permalink: /team/:name/
    output: true
  guides:
    permalink: /guides/:title/
    output: true
  playbooks:
    permalink: /playbooks/:title/
    output: true

defaults:
  - values:
      layout: page
  - scope:
      type: guides
    values:
      layout: guide
  - scope:
      type: playbooks
    values:
      layout: playbook
  - scope:
      type: team
    values:
      layout: bio
  # Exclude assets from sitemap.xml
  - scope:
      path: "assets/**"
    values:
      sitemap: false

toc:
  list_class: usa-sidenav
  sublist_class: usa-sidenav__sublist
  item_class: usa-sidenav__item

forms:
  - type: newsletter
    heading: Ask a question
    url: https://docs.google.com/a/gsa.gov/forms/d/e/1FAIpQLSesCR4CG0zSRhYLTY7Oq04PaD99Uk1rJrFjmohsW8vYwtNxiw/formResponse
    button: Send
    privacypolicy: Your privacy and security are important to us, we'll only share your information as described in the <a href="http://www.gsa.gov/portal/content/116609">GSA Privacy and Security Notice.</a>
    fields:
      - type: subject
        name: entry.1866334422
        label: Subject
      - type: text
        name: entry.143577008
        label: How can we help?
      - type: email
        name: entry.211727308
        label: Your email address

intake:
  - type: intake
    heading:
    url: https://docs.google.com/a/gsa.gov/forms/d/e/1FAIpQLScC37I1E3pCD8qXfnhUvorJKrMNRL9edezZvEYUIdPt5GE0dg/formResponse
    button: Submit
    privacypolicy: Your privacy and security are important to us, we'll only share your information as described in the <a href="http://www.gsa.gov/portal/content/116609">GSA Privacy and Security Notice.</a>
    fields:
      - type: submitter name
        name: entry.20395120
        label: Your Name
      - type: submitter email
        name: entry.525550689
        label: Your Email
      - type: problem statement
        name: entry.1314705153
        label: Problem Statement
      - type: purpose
        name: entry.1645822807
        label: Purpose
      - type: scope
        name: entry.76271973
        label: Scope
      - type: strategic goals
        name: entry.285185669
        label: Strategic Goals
      - type: Business Lines
        name: entry.1811656482
        label: Business Lines
      - type: name
        name: entry.460893215
        label: Stakeholder Name
      - type: email
        name: entry.639786444
        label: Stakeholder Email
      - type: phone
        name: entry.1169908858
        label: Stakeholder Phone
      - type: funds
        name: entry.1133652762
        label: Requested Funds
      - type: source
        name: entry.90307167
        label: Funding Source
