# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

title: GSA Chief Technology Officer
email: cto@gsa.gov
description: >
  The Office of the CTO utilizes collaborative practices and modern IT tools to facilitate a new GSA.

# baseurl: ""
# url: "http://cto.gsa.gov"
baseurl: "/cto-website"
url: "http://gsa.github.io"
markdown: kramdown

collections:
  team:
    permalink: /team/:name/
    output: true
  guides:
    permalink: /guides/:title/
    output: true

defaults:
  -
    values:
      layout: page
  -
    scope:
      path: ""
      type: guides
    values:
      layout: guide
