version: 2

jobs:
  build:
    working_directory: ~/cto-website
    docker:
      image: circleci/ruby:2.4
    steps:
      - checkout

      # Restore bundle cache
      - type: cache-restore
        key: cto-website-{{ checksum "Gemfile.lock" }}

      # Install dependencies
      - run: bundle install

      # Save bundle cache
      - type: cache-save
        key: cto-website-{{ checksum "Gemfile.lock" }}

      # test
      - run: bundle exec rake test:ci
